Feature/#7
Team-B1ND/dodamdodam-teacher-web pull request #23
Opened 2024-02-21 05:01 UTC by Sanghyun0505

## ⛳️ 작업 내용
버스기능을 개발 하였습니다.
- 버스 관리 기능 개발
- 버스 전체기록 조회 기능 개발
- 날짜별 버스 조회 기능 개발

## 📸 스크린샷

### 버스 관리
<img width="1512" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/21ee2f77-d517-4f02-86e6-00c9f2f05621">

### 버스 전체기록 조회
<img width="1511" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/75a1dc86-6ec8-4ecc-8163-e33cceee94ff">

### 날짜별 버스 조회
<img width="1512" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/d8431d55-0269-48c9-bdad-f8296154dc2a">

### 버스 탑승자 명단
<img width="1507" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/a97437b4-7a77-4044-8a3e-740bafd1ab47">

### 버스 등록 폼
<img width="1505" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/2163ae2b-7766-40fb-bcbc-bc8cb49e2093">

2024-02-21 14:21 UTC, HAERIM0 commented
수고하셨습니다~! 수정이 크게 필요하지는 않을것 같습니다!

하나의 의견이 있는데 이렇게 ../../ 이 보기에 깔끔해보이지 않아서 baseUrl을 src로 바꿔 
<img width="888" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/5e613dfd-5177-45b0-958f-ff835ed1c187">

<img width="760" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/3a53c668-80db-45b4-a858-8a291b8cac02">

이런식으로 바꾸는건 어떨지 두분의 의견이 궁금합니다~

2024-02-21 14:23 UTC, HAERIM0 commented
추가로 궁금한 것이 있어 질문 남깁니다.

상현님은 커밋 메세지를 대부분 chore를 쓰시는데 chore의 의미는 빌드 없무 수정,패키지 매니저 수정(프로덕션 코드 변경 X)로 알고있습니다. 
새로운 기능을 추가했을 때는 feat를 써도 될것 같은왜 chore을 쓰시는 이유가 있나요??

2024-02-21 15:29 UTC, Sanghyun0505 commented
바인드 디스코드에 올라온 커밋메세지에 자잘한 수정일 때 chore를 사용한다고 올라와 있습니다!
그래서 제가 chore로 올린 커밋메시지를 보시면 메인 핵심 기능 개발에 크게 관여를 하지 않는 것들이 chore로 커밋되어 있는 것을 확인할 수 있습니다. 

어랏.. 근데 지금 커밋 메시지를 보니까 스타일링과 버스 전체기록 조회 기능 커밋 메세지가 잘못됬네요 ㅜㅜ
다음부터는 실수하지 않도록 하겠습니다ㅜㅜㅜ

baseUrl을 src로 설정하는 것도 좋은 방법이네요! 피드백 반영으로 적용해놓겠습니다~~

2024-02-22 02:57 UTC, BaekSeungHa requested changes
수고하셨습니다~
코멘트 한 번 확인해주세요

2024-02-22 02:57 UTC, BaekSeungHa commented on src/components/Bus/BusDate/BusDateItem/index.tsx
> +  const dateBusData = data?.data.bus;
```suggestion
  const { data : dateBusData } = useGetBusDateQuery(handleConvertToBusParamFormat(), {
    suspense: true,
  }).data?.data.bus;
  
```

2024-02-22 02:57 UTC, BaekSeungHa commented on src/components/Bus/BusList/BusListItem/index.tsx
> +  const busData = data?.data.bus;
이것도

2024-02-22 02:57 UTC, BaekSeungHa commented on src/components/Bus/BusModal/BusPassenger/index.tsx
> +  }, [busPassengerData]);
함수로 빼면 좋을것 같습니다. 컴포넌트에는 UI 관련 로직만 있는게 좋을것 같습니다

2024-02-22 02:57 UTC, BaekSeungHa commented on src/hooks/Bus/useRegistBus.ts
> +    }
너무 길어지는데 이것도 빼면 좋을것 같습니다

2024-02-22 02:57 UTC, BaekSeungHa commented on src/hooks/Bus/useSearchBus.ts
> +export const useSearchBus = () => {
```suggestion
export const useSearchBusByBusName = () => {
```
어떤가요?

2024-02-22 06:25 UTC, Sanghyun0505 commented on src/hooks/Bus/useRegistBus.ts
> +    }
함수로 빼두었습니다!

2024-02-22 06:27 UTC, Sanghyun0505 commented on src/hooks/Bus/useSearchBus.ts
> +export const useSearchBus = () => {
오 좋네요 useSearchBusByBusName 경우는 BusManagementItem에서 밖에 사용하지 않는데

<img width="225" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/f1504ac0-3297-421a-a654-0954dc7cfdb9">

이렇게 관리하는게 더 좋을 것 같은데 어떠신가요??

2024-02-22 06:28 UTC, Sanghyun0505 commented on src/components/Bus/BusModal/BusPassenger/index.tsx
> +  }, [busPassengerData]);
넵 수정했습니다!

2024-02-22 06:44 UTC, Sanghyun0505 commented on src/components/Bus/BusDate/BusDateItem/index.tsx
> +  const dateBusData = data?.data.bus;
<img width="538" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/104070112/e8d533ea-5e44-4e30-ba2d-2c0a59e04322">

data의 bus 객체를 가지고 오기 때문에 비구조화 할당은 사용하지 못하네요,, 대신 일반변수에 할당하도록 하겠습니다!

2024-02-22 15:20 UTC, BaekSeungHa commented on src/hooks/Bus/useSearchBus.ts
> +export const useSearchBus = () => {
HOOKS 폴더에 관리하는게 좋아보입니다 하나의 컴포넌트에만 사용되는 커스텀 훅들도 HOOKS 폴더에서 관리하고 있다고 생각합니다

2024-02-23 11:30 UTC, BaekSeungHa approved these changes

2024-02-23 11:33 UTC, HAERIM0 approved these changes

2024-02-23 11:38 UTC, Sanghyun0505 commented on src/components/common/ExtractCsvData/index.tsx
> +interface Props {
넵

2024-02-23 11:39 UTC, Sanghyun0505 commented on src/components/Bus/BusModal/BusPassenger/index.tsx
> +interface Props {
넵

2024-02-23 11:39 UTC, Sanghyun0505 commented on src/components/Bus/BusModal/BusRegister/BusRegisterForm/index.tsx
> +interface Props {
넵

2024-02-23 13:40 UTC, Sanghyun0505 commented on src/components/Bus/BusDate/index.tsx
> +        <input
버스 기능 중에 캘린더로 시간을 지정하는 기능이 있는데 react-calender는 시간을 지정하는 기능이 없어서 해림님이 리액트 내부 캘린더로 수정하시면 그때 반영하도록 하겠습니다!!

2024-02-23 13:42 UTC, merged