Origin/feature/#4
Team-B1ND/dodamdodam-teacher-web pull request #24
Opened 2024-02-21 13:07 UTC by HAERIM0

## ⛳️ 작업 내용

- 외출 기능 개발
- 외박 기능 개발
- 외박중 기능 개발

- 외출,외박의 복귀 처리 기능이 없어졌습니다.

## 📸 스크린샷

<img width="1797" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/5b07efa7-dbae-46d2-80b6-98354e7a0930">

<img width="1793" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/9b6459d1-19a6-4c2b-9e40-3e97ed903c93">

2024-02-21 17:18 UTC, Sanghyun0505 requested changes
기능 구현 하시느라 정말정말 수고많으셨습니다!! 👍 
피드백 반영은 모두 다 해주실 필요는 없습니다.(지극히 저의 개인의사가 많이 들어가 있기에 ㅎㅎ 😎) 
반영하셨다면 다시 요청해주세요 ~~!!
그럼, 저는 코드리뷰 여기서 마무리 짓도록 하겠습니다 ㅎㅎㅎ

아 그리고, 커밋할 때 이슈 넘버로 커밋하는 거 엄청 좋은 것 같네요!! 저도 한번 써보겠슴다!!! 🤩

2024-02-21 17:23 UTC, Sanghyun0505 requested changes

2024-02-21 17:23 UTC, Sanghyun0505 commented on src/components/OffBase/OffBasePass/index.tsx
> +  const [studentName, setStudentName] = useState<string>("");
추가로 ts는 타입추론이 있기에  string타입을 지정안해도 될 것 같습니다~!

2024-02-22 03:25 UTC, BaekSeungHa approved these changes
고생고생요~~

2024-02-22 03:25 UTC, BaekSeungHa commented on src/components/OffBase/OffBaseLeave/OffBaseLeaveItem/index.tsx
> +  const { data: OffBaswPass } = useGetOffBasePassQuery(uploadDate);
```suggestion
  const { data: offBaswPass } = useGetOffBasePassQuery(uploadDate);
```
카멜케이스 사용하는게 어떨까요

2024-02-22 03:25 UTC, BaekSeungHa commented on src/components/OffBase/OffBasePass/index.tsx
> +        <div style={{ display: "flex" }}>
Flex 컴포넌트 사용하면 좋을것 같습니다

2024-02-22 12:58 UTC, HAERIM0 commented on src/components/OffBase/OffBasePass/index.tsx
> +  const [studentName, setStudentName] = useState<string>("");
타입 추론을 이용하면 되지만 같이 개발하는 팀원들의 입장에서는 저렇게 지정해놓으면 훨씬 직관적일 것 같다고 생각했는데 어떻게 생각하시나용

2024-02-22 12:58 UTC, HAERIM0 commented on src/queries/OffBasePass/offbasepass.query.ts
> +      cacheTime: 1000 * 60 * 60,
수정했습니당 :)

2024-02-22 13:03 UTC, HAERIM0 commented on src/components/common/Calendars/index.tsx
> +  );
react-calender에는 내장되어있는 기능 ex) 오늘 날짜에 색 표시, 등등 스타일링쪽이 잘 되어있어 편해서 사용을 했었습니다. 하지만 이번 기능 구현 이후에 라이브러리를 삭제하고 캘린터를 수정할 예정입니다~~!! 상현님도 캘린더 사용해야되는 부분에 저 공통 컴포넌트를 사용해 주셨으면 합니다~!

2024-02-22 13:19 UTC, HAERIM0 commented on src/components/OffBase/TodayOffBase/TodayOffBaseItem/index.tsx
> +    moment().format("YYYY-MM-DD")
moment.js 라이브러리가 크기가 큰지 몰랐는데 감사합니다~~ 
일단 머지하기전이라 dayjs 사용해서 수정하고 moment는 지웠습니다~ 버스 머지하면 저걸로 바꾸도록 할게요

2024-02-22 13:23 UTC, HAERIM0 commented on src/components/common/Calendars/style.ts
> +    transition: color 0.5s ease-in, border-color 0.1s ease-in;
원래 캘린더에 마우스포인터를 가져다대면 색이 나타나게 하느라 저걸 사용했었는데 지금은 필요없는 코드입니다!!

2024-02-22 13:27 UTC, HAERIM0 commented on src/components/OffBase/OffBasePass/OffBasePassItem/index.tsx
> +  selectApproval: any;
테스트 하면서 any타입을 지정했다가 안지웠던것 같습니다~~ 수정했습니다 :)

2024-02-22 13:28 UTC, HAERIM0 commented on src/queries/OffBasePass/offbasepass.query.ts
> +    string | any
헉쓰 수정했습니당 :)

2024-02-22 13:31 UTC, HAERIM0 commented on src/components/OffBase/OffBasePass/OffBasePassItem/index.tsx
> +      );
원래는 그렇게 되어있었는데 ALLOWED,PENDING,DENIED  이 3가지 상태에따라 나오는 UI가 모두 달라서 if else문을 사용했습니다!! 더 좋은 의견 있으시면 말해주세요~!

2024-02-22 13:32 UTC, HAERIM0 commented on src/components/OffBase/OffBaseLeave/OffBaseLeaveItem/index.tsx
> +  const { data: OffBaswPass } = useGetOffBasePassQuery(uploadDate);
오타 수정이랑 같이 수정했습니다 :)

2024-02-22 13:34 UTC, HAERIM0 commented on src/components/OffBase/OffBasePass/index.tsx
> +          )}
수정했습니다 ~~ 감사합니다 :)

2024-02-22 13:37 UTC, HAERIM0 commented on src/components/OffBase/OffBasePass/index.tsx
> +        <div style={{ display: "flex" }}>
이거 혹시 display : flex가 있는 저 div에 사용하라는 말씀이신가요~?

2024-02-22 14:02 UTC, HAERIM0 commented on src/hooks/OffBase/OffBaseLeave/useOffBaseLeave.ts
> +
저 검사로직은 query라는 파라미터와 query를 직접 비교하기때문에 함수로 빼는건 조금 어렵습니다.
export const offBaseQueryCheck = (query: any) => {
  switch (query) {
    case "patchLeaveApproval":
      B1ndToast.showSuccess("외박 승인 성공");
      break;
    case "patchLeaveCancel":
      B1ndToast.showSuccess("외박 거절 성공");
      break;
    case "patchLeaveApprovalCancel":
      B1ndToast.showSuccess("외박 승인 취소 성공");
      break;
  }
};


switch문을 사용하면 이런식으로 사용을 하는데 저 ts파일에서는 query를 직접 불러오지 않아 문자열로 케이스를 작성하게 됩니다. 이러한 경우에는 동작을 하지 않더라구요~~~ 혹시 틀린게 있다면 알려주세요~!

2024-02-22 14:45 UTC, Sanghyun0505 commented on src/hooks/OffBase/OffBaseLeave/useOffBaseLeave.ts
> +
아하 그러면 그대로 놔둬도 괜찮을 것 같네요!

2024-02-22 14:46 UTC, Sanghyun0505 commented on src/components/common/Calendars/index.tsx
> +  );
넵 알겠습니다

2024-02-22 14:49 UTC, BaekSeungHa commented on src/components/OffBase/OffBasePass/index.tsx
> +        <div style={{ display: "flex" }}>
yes

2024-02-22 14:50 UTC, Sanghyun0505 commented on src/components/OffBase/OffBasePass/index.tsx
> +  const [studentName, setStudentName] = useState<string>("");
오오 저 같은 경우엔 해당 useState를 봤을 때 초기값이 문자열이기도 해서 한눈에 string 타입이란 것을 알 수 있었던 것 같아서 타입을 지정을 하지 않아도 된다고 생각합니당..

2024-02-22 16:18 UTC, Sanghyun0505 approved these changes

2024-02-23 03:56 UTC, merged