Origin/feature/#5
Team-B1ND/dodamdodam-teacher-web pull request #27
Opened 2024-02-25 12:47 UTC by HAERIM0

## ⛳️ 작업 내용

- 심자 수락 (피드백 반영하면서 머지 해버렸습니다 ㅜㅜ 코드 같이 봐주세요~)
- 심자중 조회
- 심자 인원 엑셀 뽑기

## 📸 스크린샷

<img width="1796" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/f14673eb-b663-4d7f-97f5-d5eadc565a55">

<img width="1789" alt="image" src="https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101709981/5f13ddc1-9ca3-4905-a87c-36488a2d5fec">

2024-02-25 13:20 UTC, Sanghyun0505 requested changes
겨울방학 영남이공대 캠프에서 얘기가 나왔었는데 심자는 latenight 말고 nightstudy를 사용하기로 하였습니다! nightstudy로 수정해주시고 나머지 피드백 반영해서 다시 요청해주세요~

2024-02-25 13:20 UTC, Sanghyun0505 commented on src/hooks/Bus/useBusPassenger.ts
> +    console.log(busPassengerData);
콘솔 지워주세요~

2024-02-25 13:20 UTC, Sanghyun0505 commented on src/components/LateNight/LateNightToday/index.tsx
> +          <Suspense fallback={<>로딩중...</>}>
스켈레톤을 적용해보는건 어떨까요?

2024-02-26 06:20 UTC, BaekSeungHa requested changes
고생하셨습니다 수정하고 다시 코드리뷰 요청해주세요

2024-02-26 06:20 UTC, BaekSeungHa commented on src/components/LateNight/LateNightAllow/LateNightAllowItem/index.tsx
> +    setIsOpen(!isOpen);
```suggestion
    setIsOpen(true);
```
명시적으로 보여주는게 나아보입니다 !isOpen은 useState에 초기값을 봐아 알 수 있기 때문에요

2024-02-26 06:20 UTC, BaekSeungHa commented on src/components/LateNight/LateNightToday/LateNightTodayItem/index.tsx
> +    setIsOpen(!isOpen);
이것도 마찬가지네요

2024-02-26 06:20 UTC, BaekSeungHa commented on src/components/LateNight/LateNightToday/index.tsx
> +  console.log(lateNightInfo);
콘솔 지워주세요

2024-02-26 06:20 UTC, BaekSeungHa commented on src/hooks/LateNight/useLateNightStudent.ts
> +};
무엇을 하는 함수인가요? 네이밍을 더 명확하게 할 필요가 있을 것 같습니다.

2024-02-26 06:20 UTC, BaekSeungHa commented on src/components/Bus/BusModal/BusRegistForm/index.tsx
> +export default BusRegistForm;
사용하는 컴포넌트인가요?

2024-02-26 06:44 UTC, HAERIM0 commented on src/hooks/LateNight/useLateNightStudent.ts
> +};
수정했습니다 :)

2024-02-26 06:45 UTC, HAERIM0 commented on src/components/LateNight/LateNightToday/index.tsx
> +          <Suspense fallback={<>로딩중...</>}>
스켈레톤 공통 컴포넌트로 빼놓았습니다 ~~ :)

2024-02-26 06:45 UTC, HAERIM0 commented on src/components/LateNight/LateNightAllow/LateNightAllowItem/index.tsx
> +    setIsOpen(!isOpen);
수정했습니다 :)

2024-02-26 06:45 UTC, HAERIM0 commented on src/components/LateNight/LateNightToday/index.tsx
> +  console.log(lateNightInfo);
수정했습니다 :)

2024-02-26 10:01 UTC, Sanghyun0505 approved these changes

2024-02-26 10:03 UTC, merged