상벌점, 일정 관리 퍼블리싱 및 1차 구현
Team-B1ND/dodamdodam-teacher-web pull request #37
Opened 2024-03-16 09:05 UTC by BaekSeungHa

## ⛳️ 작업 내용

- 상벌점 조회 , 학생 상벌점 상세보기 확인
- 학생 상벌점 부여 로직 구현
- 상벌점 사유 등록, 불러오기 구현
- 일정 불러오기, 생성 구현
- 테이블 뷰 구현(퍼블리싱 미완성) 

## 📸 스크린샷

![스크린샷 2024-03-16 오후 6 04 47](https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101560680/fe1e92eb-6f59-4437-8713-97f63b43741c)
![스크린샷 2024-03-16 오후 6 05 02](https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101560680/a76a6121-d875-4ac6-8f99-2f8c61acf1cb)
![스크린샷 2024-03-16 오후 6 05 11](https://github.com/Team-B1ND/dodamdodam-teacher-web/assets/101560680/d940f572-2740-46df-a4d8-7c755fca813a)

2024-03-16 10:23 UTC, Sanghyun0505 requested changes
수고하셨습니다. 피드백 반영해주시고 다시 코드리뷰 요청 부탁드립니다. 
추가로 코드 컨벤션에 따르면 query나 type의 네이밍은 point.query.ts, point.type.ts으로 지정해야한다고 정리되었는데 query.ts, type.ts로 하신 이유가 있는지 궁금합니다.

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/Modal/constant.ts
> +import styled from "styled-components";
import styled from "styled-components";는 필요없는 import인 것 같습니다. 삭제해주세요!

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/PointReason/PointReasonForm/index.tsx
> +              value={scoreType === "" ? "타입을 선택해주세요" : scoreType}
scoreType || "타입을 선택해주세요"로 수정하셔도 될 것 같습니다.

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/PointScore/PointScoreHeader/index.tsx
> +            onChange={setGrade}
grade || "학년을 선택해주세요"로 수정하셔도 될 것 같습니다.

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/PointScore/PointScoreHeader/index.tsx
> +            value={room === "" ? "학반을 선택해주세요" : room}
room || "학반을 선택해주세요"로 수정하셔도 될 것 같습니다.

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/PointScore/PointScoreTable/index.tsx
> +  };
함수로 빼신 이유가 있을까요?

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/components/Point/PointScore/PointScoreTable/index.tsx
> +`;
background-color: ${({ isClicked }) =>
    isClicked ? "rgba(0, 103, 188, 0.08)" : "#fff"};로 수정하시면 css를 사용하지 않아도 되서 코드라인을 줄일 수 있습니다.

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/hooks/Point/useGivePointStudent.ts
> +        },
console.log말고 B1ndToast로 수정해주세요

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/queries/Point/query.ts
> +    ["point/getAllMemberPoint", type],
QueryKey를 작성하지 않은 이유가 있을까요?

2024-03-16 10:23 UTC, Sanghyun0505 commented on src/repositories/Point/PointRepository.ts
> +  scoreType: "BONUS" | "MINUS" | "OFFSET" | string;
"BONUS", "MINUS", "OFFSET" 말고 다른 타입이 오는 경우가 있을까요? 아니라면 리터럴 타입만 있는 것이 좋을 것 같습니다.

PointValueType | string으로 해도 될 것 같네요.

2024-03-16 12:08 UTC, BaekSeungHa commented on src/components/Point/PointScore/PointScoreTable/index.tsx
> +  };
test code

2024-03-16 12:10 UTC, HAERIM0 commented
일정을 직접 구현하시느라 고생 많으셨습니다~~! 상현이가 피드백을 잘해줘서 저는 2개정도만 달고 끝내겠습니다~~!!!

2024-03-16 12:22 UTC, BaekSeungHa commented on src/queries/Point/query.ts
> +    ["point/getAllMemberPoint", type],
나중에 작성하겠습니다

2024-03-16 14:52 UTC, BaekSeungHa commented on src/repositories/Point/PointRepository.ts
> +  scoreType: "BONUS" | "MINUS" | "OFFSET" | string;
급하게 하느라 놓쳤네요

2024-03-16 15:34 UTC, HAERIM0 approved these changes

2024-03-17 11:35 UTC, BaekSeungHa commented on src/queries/Point/query.ts
> +      ...options,
급하게 작성하느라 놓쳤습니다.
caheTime과 staleTime을 공부할 수 있는 계기가 되었네요.

2024-03-17 14:13 UTC, merged