feat : 상/벌점, 학사일정 에러핸들링
Team-B1ND/dodamdodam-teacher-web pull request #57
Opened 2024-05-14 15:21 UTC by BaekSeungHa

## ⛳️ 작업 내용

- 에러핸들링 작업
- 상/벌점 삼항연산자 함수 추가
- PointModal 네이밍 수정

## 📸 스크린샷

2024-05-14 15:33 UTC, Sanghyun0505 requested changes
피드백 반영하시고 다시 요청해주세요.

2024-05-14 15:33 UTC, Sanghyun0505 commented on src/utils/Point/pointPoerator.ts
> +};
함수 네이밍은 camelCase와 동사로 작성합니다.

삼항 연산자보단 switch문을 사용하는 것이 가독성이 좋을 것 같네요.

scoreType: string말고 PointValueType처럼 타입을 지정해주세요.

2024-05-15 08:29 UTC, Sanghyun0505 commented on src/utils/Point/pointFormat.ts
> +};
함수명은 동사로 만드는 것이 의도를 명확히 전달하기에 좋을 것 같습니다,, change라던가 convert를 붙여서 동사형으로,, ex) convertPointTypeToEnglish

2024-05-15 08:42 UTC, BaekSeungHa commented on src/utils/Point/pointFormat.ts
> +};
오... 좋은 지적인거 같습니다 😮

2024-05-17 07:17 UTC, Sanghyun0505 approved these changes

2024-05-17 07:18 UTC, merged